In [2]:
import os
import numpy as np 

#External library pillow is an image library 
#that has pgm support
from PIL import Image

"""
Read in images into program 
"""

#allocate image array to desired output size of 10304x400
img_arr = np.zeros([10304, 400])

#initialize iterator 
k = 0

#loop through number of participants (folders) 1-40
for i in range(1, len(os.listdir('att_faces'))):
    #loop through individual images per participant 1-10
    for j in range(1, len(os.listdir('att_faces/s'+str(i)))+1):
        #save images to variable 
        images = 'att_faces/s'+str(i)+'/'+str(j)+'.pgm'
        #load image into PIL imager 
        img = Image.open(images)
        #assigned temp image to temporary numpy array 
        temp = np.array(img)
        #reshapre image to desired output size 10304x400
        img_arr[:,k] = np.reshape(temp, (temp.shape[0] * temp.shape[1]))
        #update iterator 
        k += 1

#print out shape to verify size 
img_arr.shape

(10304, 400)

In [3]:
#convert image matrix img_arr to float 
img_arr.astype(float)

array([[ 48.,  60.,  39., ..., 125., 119., 125.],
       [ 49.,  60.,  44., ..., 119., 120., 124.],
       [ 45.,  62.,  53., ..., 124., 120., 124.],
       ...,
       [ 47.,  32.,  29., ...,  36.,  89.,  36.],
       [ 46.,  34.,  26., ...,  39.,  94.,  35.],
       [ 46.,  34.,  29., ...,  40.,  85.,  34.]])

In [4]:
img_arr[:,0:2]

array([[48., 60.],
       [49., 60.],
       [45., 62.],
       ...,
       [47., 32.],
       [46., 34.],
       [46., 34.]])

In [9]:
"""
Separating the datasets 
"""
test_set = np.zeros([10304,80])
train_set = np.zeros([10304,160])
gallery_set = np.zeros([10304,160])

k = 0

for j in range(0,391,10):
    test_set[:,k] = img_arr[:,j]
    k += 1
    test_set[:,k] = img_arr[:,j+1] 
    k += 1 
k = 0

for j in range(0, 391,10):
    train_set[:,k] = img_arr[:,j+2]
    k += 1 
    train_set[:,k] = img_arr[:,j+3]
    k += 1 
    train_set[:,k] = img_arr[:,j+4]
    k += 1 
    train_set[:,k] = img_arr[:,j+5]
    k += 1
    
k = 0
for j in range(0, 391, 10):
    gallery_set[:,k] = img_arr[:,j+6]
    k += 1
    gallery_set[:,k] = img_arr[:,j+7]
    k += 1
    gallery_set[:,k] = img_arr[:,j+8]
    k += 1
    gallery_set[:,k] = img_arr[:,j+9]
    k += 1

In [10]:
test_set

array([[ 48.,  60.,  35., ...,  75., 119., 127.],
       [ 49.,  60.,  36., ...,  77., 121., 131.],
       [ 45.,  62.,  37., ...,  75., 123., 128.],
       ...,
       [ 47.,  32., 144., ..., 116.,  36.,  94.],
       [ 46.,  34., 147., ..., 114.,  40.,  84.],
       [ 46.,  34., 143., ..., 113.,  36.,  89.]])

In [11]:
train_set

array([[ 39.,  63.,  64., ..., 130., 128., 123.],
       [ 44.,  53.,  76., ..., 123., 125., 121.],
       [ 53.,  35.,  80., ..., 127., 125., 126.],
       ...,
       [ 29.,  41.,  35., ...,  33.,  85.,  40.],
       [ 26.,  10.,  37., ...,  37.,  90.,  35.],
       [ 29.,  24.,  39., ...,  40.,  84.,  42.]])

In [12]:
gallery_set

array([[ 41.,  44.,  42., ..., 125., 119., 125.],
       [ 47.,  43.,  41., ..., 119., 120., 124.],
       [ 47.,  32.,  44., ..., 124., 120., 124.],
       ...,
       [ 35.,  43.,  42., ...,  36.,  89.,  36.],
       [ 37.,  43.,  43., ...,  39.,  94.,  35.],
       [ 38.,  37.,  41., ...,  40.,  85.,  34.]])